# Limine Configuration File
# SPACE-OS

# Timeout before autoboot (seconds)
timeout: 5

# Default boot entry
default_entry: 1

# ==========================================
# SPACE-OS
# ==========================================

/Vib-OS
    protocol: limine
    kernel_path: boot():/boot/vib-os.elf
