/* Auto-generated by embed_apps.py */

#ifndef _EMBEDDED_APPS_H
#define _EMBEDDED_APPS_H

extern const unsigned char init_bin[];
extern const unsigned int init_bin_len;
extern const unsigned char login_bin[];
extern const unsigned int login_bin_len;
extern const unsigned char shell_bin[];
extern const unsigned int shell_bin_len;

#endif
