#!/usr/bin/env python3
import os
import sys

def embed_file(name, path, out_c, out_h):
    try:
        with open(path, "rb") as f:
            data = f.read()
    except FileNotFoundError:
        print(f"Warning: {path} not found, skipping")
        return

    out_c.write(f"/* {name} ({len(data)} bytes) */\n")
    out_c.write(f"const unsigned char {name}[] = {{\n")
    
    for i, byte in enumerate(data):
        out_c.write(f"0x{byte:02x},")
        if (i + 1) % 16 == 0:
            out_c.write("\n")
            
    out_c.write("\n};\n")
    out_c.write(f"const unsigned int {name}_len = {len(data)};\n\n")
    
    out_h.write(f"extern const unsigned char {name}[];\n")
    out_h.write(f"extern const unsigned int {name}_len;\n")

def main():
    if len(sys.argv) < 3:
        print("Usage: embed_apps.py <build_dir> <kernel_dir>")
        sys.exit(1)
        
    build_dir = sys.argv[1]
    kernel_dir = sys.argv[2]
    
    apps = [
        ("init_bin", os.path.join(build_dir, "userspace/sbin/init")),
        ("login_bin", os.path.join(build_dir, "userspace/bin/login")),
        ("shell_bin", os.path.join(build_dir, "userspace/bin/sh")),
    ]
    
    c_path = os.path.join(kernel_dir, "apps/embedded_apps.c")
    h_path = os.path.join(kernel_dir, "include/apps/embedded_apps.h")
    
    os.makedirs(os.path.dirname(c_path), exist_ok=True)
    os.makedirs(os.path.dirname(h_path), exist_ok=True)
    
    print(f"Generating {c_path} and {h_path}...")
    
    with open(c_path, "w") as fc, open(h_path, "w") as fh:
        fc.write("/* Auto-generated by embed_apps.py */\n\n")
        fh.write("/* Auto-generated by embed_apps.py */\n\n#ifndef _EMBEDDED_APPS_H\n#define _EMBEDDED_APPS_H\n\n")
        
        for name, path in apps:
            embed_file(name, path, fc, fh)
            
        fh.write("\n#endif\n")

if __name__ == "__main__":
    main()
